import streamlit as st
from manager.core import ANSIBLE_DIR, HOSTS_INI_FILE, load_current_config, update_yaml_config_from_schema
from manager.utils import run_shell_stream

def render_deploy():
    st.title("Deploy & Manage")
    
    tab1, tab2 = st.tabs(["Deploy", "Emergency Cleanup"])
    
    with tab1:
        st.warning("⚠️ This will overwrite existing configurations on target servers.")
        
        # Role Toggles
        st.subheader("Enabled Components")
        roles_dir = ANSIBLE_DIR / "roles"
        if roles_dir.exists():
            all_roles = sorted([d.name for d in roles_dir.iterdir() if d.is_dir()])
        else:
            all_roles = []
            
        current_config = load_current_config()
        enabled = current_config.get('enabled_roles', all_roles)
        
        st.write("Select Roles to Deploy:")
        selected_roles = []
        role_cols = st.columns(3)
        for i, role in enumerate(all_roles):
            with role_cols[i % 3]:
                if st.toggle(role, value=(role in enabled), key=f"role_toggle_{role}"):
                    selected_roles.append(role)
        
        if st.button("Save Role Selection"):
            current_config['enabled_roles'] = selected_roles
            update_yaml_config_from_schema(current_config)
            st.toast("Roles updated!")

        st.markdown("---")
        
        if st.button("🚀 Start Deployment", type="primary"):
            playbook = ANSIBLE_DIR / "playbooks" / "experimental.yml"
            inventory = HOSTS_INI_FILE
            cmd = f"ansible-playbook {playbook} -i {inventory}"
            
            st.write("Starting Ansible Playbook...")
            ret_code, output = run_shell_stream(cmd)
            
            if ret_code == 0:
                import os
                import re
                from pathlib import Path
                
                # Attempt to retrieve credentials
                config = load_current_config()
                manager_ip = config.get('wazuh_manager_ip', '<manager_ip>')
                
                # Try reading the password file generated by playbook
                password = None
                pass_file = Path(os.environ.get('HOME')) / 'Downloads' / 'wazuh-admin-password.txt'
                
                # Regex search in the output for the debug message structure
                # "msg": [ "admin", "PASSWORD" ]
                match = re.search(r'"admin",\s+"([^"]+)"', output)
                if match:
                    password = match.group(1)
                elif pass_file.exists():
                     password = pass_file.read_text().strip().splitlines()[0] if pass_file.read_text().strip() else None

                # Only show success/password if deploying Wazuh components that generate it
                wazuh_core_roles = {'wazuh-server', 'wazuh-indexer', 'wazuh-dashboard'}
                is_wazuh_deploy = any(role in selected_roles for role in wazuh_core_roles)

                if password and is_wazuh_deploy:
                    st.success("Deployment Successful!")
                    
                    st.markdown(f"""
                    <div class="css-card" style="border-color: #34d399; background: rgba(16, 185, 129, 0.05);">
                        <h3 style="color: #34d399; margin-top: 0;">🚀 System Operational</h3>
                        <p>Your security stack is up and running.</p>
                        <div style="background: rgba(0,0,0,0.3); padding: 15px; border-radius: 8px; margin-top: 10px; border: 1px solid rgba(255,255,255,0.1);">
                            <div style="margin-bottom: 8px;"><strong>Dashboard:</strong> <a href="https://{manager_ip}" target="_blank" style="color: #38bdf8; text-decoration: none; font-weight: bold;">https://{manager_ip}</a></div>
                            <div style="margin-bottom: 8px;"><strong>Username:</strong> <code style="color: #e2e8f0; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px;">admin</code></div>
                            <div><strong>Password:</strong> <code style="color: #fca5a5; font-weight: bold; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px;">{password}</code></div>
                        </div>
                        <p style="font-size: 0.8em; margin-top: 10px; color: #94a3b8;">
                            <i>Note: Accept the self-signed certificate warning. Credentials also saved to ~/Downloads/wazuh-admin-password.txt</i>
                        </p>
                    </div>
                    """, unsafe_allow_html=True)
                
    with tab2:
        st.error("DANGER ZONE: This will remove all components.")
        if st.button("🔥 Run Cleanup", type="primary"):
             playbook = ANSIBLE_DIR / "playbooks" / "experimental.yml"
             inventory = HOSTS_INI_FILE
             # cleanup tag
             cmd = f"ansible-playbook {playbook} -i {inventory} -e '{{\"enabled_roles\": [\"cleanup\"]}}'"
             run_shell_stream(cmd)
