{
 "title": "Security Dashboard",
 "description": "Grafana Security Dashboard",
 "tags": [
  "wazuh",
  "siem"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Ports",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "_source.agent.name", "text": "Agent", "type": "string" },
      { "selector": "_source.process.name", "text": "Process", "type": "string" },
      { "selector": "_source.process.pid", "text": "PID", "type": "number" },
      { "selector": "_source.network.transport", "text": "Protocol", "type": "string" },
      { "selector": "_source.source.ip", "text": "Local IP", "type": "number" },
      { "selector": "_source.source.port", "text": "Local port", "type": "number" },
      { "selector": "_source.interface.state", "text": "State", "type": "string" },
      { "selector": "_source.destination.ip", "text": "Remote IP", "type": "number" },
      { "selector": "_source.destination.port", "text": "Remote Port", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "https://192.168.64.12:9200/wazuh-states-inventory-ports-*/_search",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 1000,\n  \"query\": {\n    \"match_all\": {}\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Packages",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "targets": [
    {
     "columns": [
      { "selector": "_source.agent.name", "text": "Agent", "type": "string" },
      { "selector": "_source.package.name", "text": "Package", "type": "string" },
      { "selector": "_source.package.version", "text": "Version", "type": "number" },
      { "selector": "_source.package.architecture", "text": "Architecture", "type": "string" },
      { "selector": "_source.package.vendor", "text": "Vendor", "type": "string" },
      { "selector": "_source.package.description", "text": "Description", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "https://192.168.64.12:9200/wazuh-states-inventory-packages*/_search",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 1000,\n  \"query\": {\n    \"match_all\": {}\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "_source.agent.name", "text": "Agent", "type": "string" },
      { "selector": "_source.user.name", "text": "Name", "type": "string" },
      { "selector": "_source.user.password.status", "text": "Password Status", "type": "string" },
      { "selector": "_source.user.shell", "text": "Shell", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "https://192.168.64.12:9200/wazuh-states-inventory-users*/_search",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 1000,\n  \"query\": {\n    \"match_all\": {}\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Assets",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "columns": [
      { "selector": "_source.agent.name", "text": "Name", "type": "string" },
      { "selector": "_source.host.cpu.cores", "text": "CPU", "type": "string" },
      { "selector": "_source.host.memory.total", "text": "", "type": "number" },
      { "selector": "_source.host.memory.usage", "text": "", "type": "number" },
      { "selector": "_source.host.memory.free", "text": "", "type": "string" },
      { "selector": "_source.host.memory.used", "text": "", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "https://192.168.64.12:9200/wazuh-states-inventory-hardware*/_search",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 1000,\n  \"query\": {\n    \"match_all\": {}\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Assets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "_source.agent.name", "text": "Name", "type": "string" },
      { "selector": "_source.host.cpu.cores", "text": "CPU", "type": "string" },
      { "selector": "_source.host.memory.total", "text": "", "type": "number" },
      { "selector": "_source.host.memory.usage", "text": "", "type": "number" },
      { "selector": "_source.host.memory.free", "text": "", "type": "string" },
      { "selector": "_source.host.memory.used", "text": "", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "https://192.168.64.12:9200/wazuh-states-inventory-hardware*/_search",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 1000,\n  \"query\": {\n    \"match_all\": {}\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "System",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 32 },
   "targets": [
    {
     "columns": [
      { "selector": "_source.agent.name", "text": "Agent", "type": "string" },
      { "selector": "_source.host.hostname", "text": "Host", "type": "string" },
      { "selector": "_source.host.os.name", "text": "", "type": "string" },
      { "selector": "_source.host.os.version", "text": "", "type": "string" },
      { "selector": "_source.host.os.kernel.release", "text": "", "type": "string" },
      { "selector": "_source.host.architecture", "text": "", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "https://192.168.64.12:9200/wazuh-states-inventory-system*/_search",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 1000,\n  \"query\": {\n    \"match_all\": {}\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Agents and General Activity Levels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true
  },
  {
   "title": "Latest Alerts Severity Levels",
   "type": "stat",
   "description": "Latest Alerts in the past 24H",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "CRITICAL",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:15",
     "timeField": "timestamp"
    },
    {
     "alias": "HIGH",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[12 TO 14]",
     "timeField": "timestamp"
    },
    {
     "alias": "MODERATE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[6 TO 11]",
     "timeField": "timestamp"
    },
    {
     "alias": "MEDIUM",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[4 TO 6]",
     "timeField": "timestamp"
    },
    {
     "alias": "LOW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[1 TO 3]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Agents Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "agent.id", "id": "1", "type": "cardinality" }
     ],
     "query": "agent.id:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Vulnerability LVL",
   "type": "timeseries",
   "description": "Vulnerability LVL",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "LVL : 15",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:15",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  12-14",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[12 TO 14]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  6-11",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[6 TO 11]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  4-6",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[4 TO 6]",
     "timeField": "@timestamp"
    },
    {
     "alias": "LVL :  1-3",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:[1 TO 3]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules Groups",
   "type": "piechart",
   "description": "Rules Groups",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.groups",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Urgent Security Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 53 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.description",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=7",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPDR and NIST Compliance Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "NIST 800.53 Agent Count",
   "type": "piechart",
   "description": "Shows security alerts mapped to NIST standards (government security rules), highlighting areas like Login Security, System Monitoring, and Network Defense.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.nist_800_53",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GDPR Compliance Rules",
   "type": "piechart",
   "description": "Shows security alerts related to Data Privacy laws (GDPR) to highlight potential issues with personal data protection.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.gdpr",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "MITRE Compliance Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Compliance Summary (MITRE ID)",
   "type": "piechart",
   "description": "Categorizes threats by 'hacker tactics' (MITRE ATT&CK) to show what types of attacks are occurring (e.g. stealing credentials vs deleting files).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mitre Tactic",
   "type": "piechart",
   "description": "Mitre Tactic",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.tactic",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wazuh Monitoring (Agent Status)",
   "type": "stat",
   "description": "Critical. This tracks the connection status of your 50 devices. If an agent goes 'Disconnected', you need to know immediately.",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "name", "id": "2", "type": "terms" }
     ],
     "metrics": [
      { "field": "id", "id": "1", "type": "cardinality" }
     ],
     "query": "status:\"active\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Vulnerabilities ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "vulnerability.detected_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT vulnerability.under_evaluation: true AND vulnerability.severity: (\"High\" OR \"Critical\") AND NOT package.name: linux-image*",
     "timeField": "vulnerability.detected_at"
    }
   ]
  },
  {
   "title": "Wazuh Vulnerabilities (Risk)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "package.name",
       "id": "2",
       "settings": {
        "execution_hint": "map",
        "min_doc_count": "1",
        "order": "desc",
        "orderBy": "1",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": false
       },
       "type": "raw_data"
      }
     ],
     "query": "NOT vulnerability.under_evaluation: true AND vulnerability.severity: (\"High\" OR \"Critical\") AND NOT package.name: linux-image*",
     "timeField": "vulnerability.detected_at"
    }
   ]
  },
  { "title": "Tier 1: The Essentials", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Tier 2: High Value for IT Hygiene",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }
  },
  { "title": "Tier 3: Selective Use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } }
 ]
}